In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import pickle
# load model in hand_gesture_recog
with open('model.pkl', 'rb') as f:
    svm = pickle.load(f) 

In [3]:
dataset = pd.read_csv('dataset_pred.csv')

In [4]:
X = dataset.iloc[:, [0,1,2]].values

In [5]:
print(X)

[[394.   30.1  72.5]
 [394.   30.1  72.5]
 [394.   30.1  72.6]
 [394.   30.1  72.6]
 [394.   30.1  72.5]
 [394.   30.1  72.6]
 [393.   30.2  72.4]
 [394.   30.1  72.4]
 [393.   30.1  72.4]
 [393.   30.1  72.4]
 [393.   30.1  72.4]
 [393.   30.1  72.4]
 [393.   30.2  72.5]]


In [6]:
y_pred = svm.predict(X)

In [7]:
print(np.max(y_pred))


no
